// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANOAnvMvC5s-Y2hkuNzYSv1TYdzuasZs0',
    appId: '1:624494422782:web:960d1de21e2a985ab513af',
    messagingSenderId: '624494422782',
    projectId: 'flash-chat-512c9',
    authDomain: 'flash-chat-512c9.firebaseapp.com',
    storageBucket: 'flash-chat-512c9.appspot.com',
    measurementId: 'G-9Q0XC27RFH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKZ88639_U0RorHOkVbnKVizT7oquvSHE',
    appId: '1:624494422782:android:1ac7d8e9d58f6a4eb513af',
    messagingSenderId: '624494422782',
    projectId: 'flash-chat-512c9',
    storageBucket: 'flash-chat-512c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCD2B2MnYUrZpWo-CAD7s67Nubb_ALQLQ',
    appId: '1:624494422782:ios:950c063879e498ceb513af',
    messagingSenderId: '624494422782',
    projectId: 'flash-chat-512c9',
    storageBucket: 'flash-chat-512c9.appspot.com',
    iosClientId: '624494422782-mepv4pnnhgicec00u105o1ea06jav4fe.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCD2B2MnYUrZpWo-CAD7s67Nubb_ALQLQ',
    appId: '1:624494422782:ios:f1422dd6cddb1646b513af',
    messagingSenderId: '624494422782',
    projectId: 'flash-chat-512c9',
    storageBucket: 'flash-chat-512c9.appspot.com',
    iosClientId: '624494422782-kv6ljlpk2a1cka1m1pmo6kud5uini5ah.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChat.RunnerTests',
  );
}
